[package]
name = "riqaudio"
version = "0.1.0"
edition = "2021"

[lib]
name = "riqaudio"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniaudio = { version = "0.10.0", features = ["ma-enable-vorbis"] }